# https://github.com/webhooked/kanso.nvim/blob/main/extras/yazi/kanso-ink.yazi/flavor.toml

[manager]
marker_copied = { fg = "#87A987", bg = "#87A987" }
marker_cut = { fg = "#E46876", bg = "#E46876" }
marker_marked = { fg = "#938AA9", bg = "#938AA9" }
marker_selected = { fg = "#B98D7B", bg = "#B98D7B" }

cwd = { fg = "#E6C384" }
hovered = { reversed = true }
preview_hovered = { reversed = true }

find_keyword = { fg = "#B98D7B", bg = "#14171D" }
find_position = {}

tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

count_copied = { fg = "#14171D", bg = "#87A987" }
count_cut = { fg = "#14171D", bg = "#E46876" }
count_selected = { fg = "#14171D", bg = "#E6C384" }

border_symbol = "â”‚"
border_style = { fg = "#C5C9C7" }


[mode]
normal_main = { fg = "#14171D", bg = "#8BA4B0" }
normal_alt = { fg = "#8BA4B0", bg = "#14171D" }
select_main = { fg = "#14171D", bg = "#957fb8" }
select_alt = { fg = "#957fb8", bg = "#14171D" }
unset_main = { fg = "#14171D", bg = "#e6c384" }
unset_alt = { fg = "#e6c384", bg = "#14171D" }


[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "#C5C9C7", bg = "#14171D" }

progress_label = { fg = "#8BA4B0", bg = "#14171D", bold = true }
progress_normal = { fg = "#14171D", bg = "#14171D" }
progress_error = { fg = "#14171D", bg = "#14171D" }

perm_type = { fg = "#87A987" }
perm_read = { fg = "#E6C384" }
perm_write = { fg = "#E46876" }
perm_exec = { fg = "#7AA89F" }
perm_sep = { fg = "#938AA9" }


[pick]
border = { fg = "#7fb4ca" }
active = { fg = "#938AA9", bold = true }
inactive = {}

[input]
border = { fg = "#7fb4ca" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#7fb4ca" }
active = { reversed = true }
inactive = {}

[tasks]
border = { fg = "#7fb4ca" }
title = {}
hovered = { fg = "#938AA9" }

[which]
cols = 2
separator = " - "
separator_style = { fg = "#A4A7A4" }
mask = { bg = "#14171D" }
rest = { fg = "#A4A7A4" }
cand = { fg = "#8EA4A2" }
desc = { fg = "#C5C9C7" }

[help]
on = { fg = "#7AA89F" }
run = { fg = "#938AA9" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#14171D", bg = "#C5C9C7" }

[notify]
title_info = { fg = "#87A987" }
title_warn = { fg = "#E6C384" }
title_error = { fg = "#E46876" }

[filetype]
rules = [
    # images
    { mime = "image/*", fg = "#E6C384" },

    # media
    { mime = "{audio,video}/*", fg = "#938AA9" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#e46876" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#A292A3" },

    # broken links
    { name = "*", is = "orphan", fg = "#E46876" },

    # executables
    { name = "*", is = "exec", fg = "#7AA89F" },

    # fallback
    { name = "*", fg = "#C5C9C7" },
    { name = "*/", fg = "#8BA4B0" },
]
